# sovereign-survival-agent/daemon/autonomous_daemon.py
"""
24/7 Autonomous Background Worker Daemon:
Continuously monitors metabolic burn, scans GitHub & Algora for high-EV paid bounties,
executes closed-loop verification repairs in sandboxes, dispatches PRs, and triggers mobile alerts.
"""
from __future__ import annotations
import time
import threading
from typing import Dict, Any, List, Optional
from pydantic import BaseModel, Field
from core.models import AgentState, Bounty, TaskType, ModelTier
from core.metabolism import MetabolismManager
from core.policy_engine import SurvivalPolicyEngine
from core.notifier import AgentNotifier
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from channels.automated_contract_auditor import AutomatedContractAuditor


class DaemonStatus(BaseModel):
    is_running: bool
    interval_seconds: int
    total_ticks_completed: int
    bounties_scanned: int
    bounties_solved: int
    contracts_audited: int = 0
    total_revenue_claimed: float
    last_tick_time: Optional[str] = None
    last_activity_summary: str = "Daemon Initialized"


class AutonomousDaemon:
    """
    Autonomous background worker that manages 24/7 bounty hunting, smart contract auditing, and metabolism.
    """

    def __init__(
        self,
        metabolism: MetabolismManager,
        policy: SurvivalPolicyEngine,
        notifier: AgentNotifier,
        auditor: Optional[Any] = None,
        interval_seconds: int = 300
    ):
        self.metabolism = metabolism
        self.policy = policy
        self.notifier = notifier
        self.auditor = auditor
        self.interval_seconds = interval_seconds
        
        self._is_running = False
        self._thread: Optional[threading.Thread] = None
        self._solved_bounty_ids = set()
        
        self.total_ticks = 0
        self.bounties_scanned_count = 0
        self.bounties_solved_count = 0
        self.contracts_audited_count = 0
        self.total_revenue_claimed = 0.0
        self.last_activity = "Idle"
        self.last_tick_iso: Optional[str] = None


    def start(self):
        """Starts the background worker thread."""
        if self._is_running:
            return
        self._is_running = True
        self._thread = threading.Thread(target=self._run_loop, daemon=True)
        self._thread.start()
        self.last_activity = "24/7 Autonomous Daemon Started"
        self.notifier.dispatch_alert("⚡ Autonomous Daemon Online", "Agent is now actively scanning for paid bounties 24/7.")

    def stop(self):
        """Stops the background worker thread."""
        self._is_running = False
        self.last_activity = "Autonomous Daemon Paused"

    def run_single_tick(self) -> Dict[str, Any]:
        """Executes a single metabolic cycle and bounty sweep."""
        self.total_ticks += 1
        self.last_tick_iso = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())

        # 1. Deduct hourly hosting rent
        self.metabolism.tick_metabolic_cost()

        # 2. Check if agent is alive
        if not self.metabolism.state.is_alive:
            self.last_activity = f"Agent Insolvent: {self.metabolism.state.death_cause}"
            return {"status": "INSOLVENT", "message": self.last_activity}

        # 3. Automated 24/7 Smart Contract Audit Sweep (A2A Gateway & BaseScan)
        contracts_audited_this_tick = 0
        if self.auditor:
            try:
                self.auditor.run_automated_audit_tick()
                new_audit_count = len(self.auditor.audited_contracts)
                contracts_audited_this_tick = new_audit_count - self.contracts_audited_count
                self.contracts_audited_count = new_audit_count
                
                if contracts_audited_this_tick > 0:
                    # Revenue generated by the A2A Gateway or Base Oracle is credited internally by the Auditor
                    self.last_activity = f"Tick #{self.total_ticks}: Performed {contracts_audited_this_tick} Verifiable Smart Contract Audits."
                    return {"status": "AUDITS_PERFORMED", "count": contracts_audited_this_tick}
                
            except Exception as e:
                self.last_activity = f"Audit Sweep Error: {str(e)}"
                return {"status": "ERROR", "message": self.last_activity}
                
        self.last_activity = f"Tick #{self.total_ticks}: Idle. Polling for A2A Contract Audit Requests."
        return {"status": "IDLE", "audited": 0}

    def get_status(self) -> DaemonStatus:
        """Returns the live status of the daemon."""
        return DaemonStatus(
            is_running=self._is_running,
            interval_seconds=self.interval_seconds,
            total_ticks_completed=self.total_ticks,
            bounties_scanned=self.bounties_scanned_count,
            bounties_solved=self.bounties_solved_count,
            contracts_audited=self.contracts_audited_count,
            total_revenue_claimed=round(self.total_revenue_claimed, 2),
            last_tick_time=self.last_tick_iso,
            last_activity_summary=self.last_activity
        )


    def _run_loop(self):
        """Continuous background worker loop."""
        while self._is_running:
            try:
                self.run_single_tick()
            except Exception as e:
                self.last_activity = f"Daemon Error: {str(e)}"
            
            # Sleep in 1-second intervals to allow fast graceful shutdown
            for _ in range(self.interval_seconds):
                if not self._is_running:
                    break
                time.sleep(1)
